CAMERA_CAPTURE_MODE: 1
CAMERA_EXPOSURE: 20.0
CAMERA_FRAME_RATE: 50.0
CAMERA_LINE_COUNT: 1200
CAMERA_SHUTTER: Open
CAMERA_SPATIAL_BIN: 1
CAMERA_SPECTRAL_BIN: 1
OUTPUT_FOLDER: C:\work\data\30012026
RIG_BED_END: 330.0
RIG_BED_START: 230.0
RIG_BLACK_CAL_POS_READ_ONLY: 260.0
RIG_CAM_HEIGHT: 0.0
RIG_SPEED: 403.5089218238265
RIG_TIMEOUT_READ_ONLY: 95.0
RIG_TRAVEL_SPEED_READ_ONLY: 6000.0
RIG_WHITE_CAL_POS_READ_ONLY: 250.0
