CAMERA_CAPTURE_MODE: 1
CAMERA_EXPOSURE: 19.9
CAMERA_FRAME_RATE: 60.0
CAMERA_LINE_COUNT: 2000
CAMERA_SHUTTER: Open
CAMERA_SPATIAL_BIN: 1
CAMERA_SPECTRAL_BIN: 1
OUTPUT_FOLDER: C:\work\data\30012026
RIG_BED_END: 410.06
RIG_BED_START: 230.0
RIG_BLACK_CAL_POS_READ_ONLY: 260.0
RIG_CAM_HEIGHT: 90.0
RIG_SPEED: 474.52649206482
RIG_TIMEOUT_READ_ONLY: 95.0
RIG_TRAVEL_SPEED_READ_ONLY: 6000.0
RIG_WHITE_CAL_POS_READ_ONLY: 250.0
